### ISSUE TITLE
as on root config fails

### ISSUE THREAD

**Issue by woky** [ceedubs/ficus#26]
With typesafe config 1.3.2, `as` on root config object fails. Example:
```
import com.typesafe.config.{ConfigFactory, ConfigValue}
import net.ceedubs.ficus.Ficus._

val config = ConfigFactory.parseString(
  """
foo = {
  x = 1
  y = [ 0.1 2 ]
  z = {
    a = 2
  }
}
baz = [1 2 3]
""")

// fine
val submap = config.as[Map[String, ConfigValue]]("foo")

// Exception in thread "main" com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '.': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
val map1 = config.as[Map[String, ConfigValue]]

// same as above
val map2 = config.as[Map[String, ConfigValue]]("")
```

Here's the scaste: https://scastie.scala-lang.org/9VG0LqRGQzmbCQ00OHxqfw

Full error:
```
Exception in thread "main" com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '.': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
	at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:170)
	at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:74)
	at com.typesafe.config.impl.PathParser.parsePath(PathParser.java:61)
	at com.typesafe.config.impl.Path.newPath(Path.java:230)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:192)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at net.ceedubs.ficus.readers.CollectionReaders$$anon$2.read(CollectionReaders.scala:28)
	at net.ceedubs.ficus.readers.CollectionReaders$$anon$2.read(CollectionReaders.scala:26)
	at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
	at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
	at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:21)
	at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:12)
	at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:12)
	at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:21)
	at fed.FicusRoot$.delayedEndpoint$fed$FicusRoot$1(FicusRoot.scala:25)
	at fed.FicusRoot$delayedInit$body.apply(FicusRoot.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at fed.FicusRoot$.main(FicusRoot.scala:7)
	at fed.FicusRoot.main(FicusRoot.scala)
```

I'm currently getting familiar with the library. Possible use case would be mapping the whole config to a simple case class. I think I saw in the README that mapping to arbitrary classes is supported.

**Comment by woky** [comment]
Will post in the current repo
